name = "camp-paradise"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "camp-paradise-db"
database_id = "4765e73d-b7f2-4ad7-8a54-fe6966050456"
migrations_dir = "drizzle"

[vars]
PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAAEzKpCgc4kC9UW8O"
TURNSTILE_HOSTNAMES = "camp-paradise.pages.dev"
