/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ADMIN_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWS_BUCKET_NAME": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWS_DEFAULT_REGION": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FFAWS": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "MAIL_INFO_USER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MEDIA_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "SMTP_FROM": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_PORT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_USER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "bratstvousa": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "bratstvousa-bruh": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}