// Canonical Synodal (Protestant 66-book) numbering, matching getbible.net v2 book_nr.
// Maps normalized Russian abbreviations (and common variants/typos) to a book id.

export interface BookInfo {
	nr: number; // getbible book_nr
	name: string; // canonical Russian name
	singleChapter?: boolean; // books cited by verse only (Авдия, Филимон, 2/3 Ин, Иуды)
}

// Ordered canonical list. nr is 1-based in Protestant order.
export const BOOKS: BookInfo[] = [
	{ nr: 1, name: 'Бытие' },
	{ nr: 2, name: 'Исход' },
	{ nr: 3, name: 'Левит' },
	{ nr: 4, name: 'Числа' },
	{ nr: 5, name: 'Второзаконие' },
	{ nr: 6, name: 'Иисус Навин' },
	{ nr: 7, name: 'Судьи' },
	{ nr: 8, name: 'Руфь' },
	{ nr: 9, name: '1 Царств' },
	{ nr: 10, name: '2 Царств' },
	{ nr: 11, name: '3 Царств' },
	{ nr: 12, name: '4 Царств' },
	{ nr: 13, name: '1 Паралипоменон' },
	{ nr: 14, name: '2 Паралипоменон' },
	{ nr: 15, name: 'Ездра' },
	{ nr: 16, name: 'Неемия' },
	{ nr: 17, name: 'Есфирь' },
	{ nr: 18, name: 'Иов' },
	{ nr: 19, name: 'Псалтирь' },
	{ nr: 20, name: 'Притчи' },
	{ nr: 21, name: 'Екклесиаст' },
	{ nr: 22, name: 'Песня Песней' },
	{ nr: 23, name: 'Исаия' },
	{ nr: 24, name: 'Иеремия' },
	{ nr: 25, name: 'Плач Иеремии' },
	{ nr: 26, name: 'Иезекииль' },
	{ nr: 27, name: 'Даниил' },
	{ nr: 28, name: 'Осия' },
	{ nr: 29, name: 'Иоиль' },
	{ nr: 30, name: 'Амос' },
	{ nr: 31, name: 'Авдий', singleChapter: true },
	{ nr: 32, name: 'Иона' },
	{ nr: 33, name: 'Михей' },
	{ nr: 34, name: 'Наум' },
	{ nr: 35, name: 'Аввакум' },
	{ nr: 36, name: 'Софония' },
	{ nr: 37, name: 'Аггей' },
	{ nr: 38, name: 'Захария' },
	{ nr: 39, name: 'Малахия' },
	{ nr: 40, name: 'От Матфея' },
	{ nr: 41, name: 'От Марка' },
	{ nr: 42, name: 'От Луки' },
	{ nr: 43, name: 'От Иоанна' },
	{ nr: 44, name: 'Деяния' },
	// getbible NT order: Pauline epistles first, then general epistles, then Revelation
	{ nr: 45, name: 'Римлянам' },
	{ nr: 46, name: '1 Коринфянам' },
	{ nr: 47, name: '2 Коринфянам' },
	{ nr: 48, name: 'Галатам' },
	{ nr: 49, name: 'Ефесянам' },
	{ nr: 50, name: 'Филиппийцам' },
	{ nr: 51, name: 'Колоссянам' },
	{ nr: 52, name: '1 Фессалоникийцам' },
	{ nr: 53, name: '2 Фессалоникийцам' },
	{ nr: 54, name: '1 Тимофею' },
	{ nr: 55, name: '2 Тимофею' },
	{ nr: 56, name: 'Титу' },
	{ nr: 57, name: 'Филимону', singleChapter: true },
	{ nr: 58, name: 'Евреям' },
	{ nr: 59, name: 'Иакова' },
	{ nr: 60, name: '1 Петра' },
	{ nr: 61, name: '2 Петра' },
	{ nr: 62, name: '1 Иоанна' },
	{ nr: 63, name: '2 Иоанна', singleChapter: true },
	{ nr: 64, name: '3 Иоанна', singleChapter: true },
	{ nr: 65, name: 'Иуды', singleChapter: true },
	{ nr: 66, name: 'Откровение' }
];

// Normalized abbreviation -> book_nr. Keys are lowercase, no trailing dot,
// spaces collapsed. Numbered-book prefixes like "1", "2", "3" are kept as
// part of the key (e.g. "1 иоан").
export const ABBREV_TO_NR: Record<string, number> = {
	// Pentateuch / history
	быт: 1,
	бытие: 1,
	исх: 2,
	исход: 2,
	лев: 3,
	левит: 3,
	числ: 4,
	чис: 4,
	числа: 4,
	втор: 5,
	нав: 6,
	'иис нав': 6,
	'и нав': 6,
	суд: 7,
	судей: 7,
	руф: 8,
	руфь: 8,
	'1 цар': 9,
	'1цар': 9,
	'2 цар': 10,
	'2цар': 10,
	'3 цар': 11,
	'3цар': 11,
	'4 цар': 12,
	'4цар': 12,
	'1 пар': 13,
	'1пар': 13,
	'2 пар': 14,
	'2пар': 14,
	ездр: 15,
	езд: 15,
	неем: 16,
	есф: 17,
	иов: 18,
	пс: 19,
	псал: 19,
	псалом: 19,
	притч: 20,
	прит: 20,
	еккл: 21,
	екк: 21,
	песн: 22,
	'п песн': 22,
	песнь: 22,
	// Prophets
	ис: 23,
	иса: 23,
	иер: 24,
	плач: 25,
	иез: 26,
	дан: 27,
	ос: 28,
	осия: 28,
	иоил: 29,
	иоиль: 29,
	ам: 30,
	амос: 30,
	авд: 31,
	авдия: 31,
	ион: 32,
	иона: 32,
	мих: 33,
	наум: 34,
	аввак: 35,
	авв: 35,
	соф: 36,
	агг: 37,
	зах: 38,
	мал: 39,
	// Gospels / Acts
	матф: 40,
	мат: 40,
	мф: 40,
	марк: 41,
	мк: 41,
	мар: 41,
	лук: 42,
	лк: 42,
	лука: 42,
	иоан: 43,
	ин: 43,
	иоанн: 43,
	деян: 44,
	деяния: 44,
	// Pauline
	рим: 45,
	'1 кор': 46,
	'1кор': 46,
	'2 кор': 47,
	'2кор': 47,
	гал: 48,
	еф: 49,
	ефес: 49,
	фил: 50,
	флп: 50,
	кол: 51,
	'1 фес': 52,
	'1фес': 52,
	'1 сол': 52,
	'2 фес': 53,
	'2фес': 53,
	'2 сол': 53,
	'1 тим': 54,
	'1тим': 54,
	'2 тим': 55,
	'2тим': 55,
	тит: 56,
	флм: 57,
	филим: 57,
	евр: 58,
	// Epistles (general)
	иак: 59,
	иакова: 59,
	'1 петр': 60,
	'1петр': 60,
	'1 пет': 60,
	'2 петр': 61,
	'2петр': 61,
	'2 пет': 61,
	'1 иоан': 62,
	'1иоан': 62,
	'1 ин': 62,
	'2 иоан': 63,
	'2иоан': 63,
	'2 ин': 63,
	'3 иоан': 64,
	'3иоан': 64,
	'3 ин': 64,
	иуд: 65,
	иуды: 65,
	иуда: 65,
	откр: 66,
	отк: 66
};

export function bookNrFromName(name: string): number | undefined {
	const b = BOOKS.find((x) => x.name === name);
	return b?.nr;
}
